spring:
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true

# config for H2
  datasource:
    url: jdbc:h2:mem:EMOJI

# config for PostgreSQL instance in AWS RDS
  #datasource:
    #url: jdbc:postgresql://databasejng1.cdmn6rqnxb8c.eu-west-3.rds.amazonaws.com:5432/jngdb
    #url: jdbc:postgresql://15.237.165.6:5432/jngdb
    #username: postgresjng1
    #password: postgresjng1pwd

# config for PostgreSQL instance as helm chart on TKGs
  #datasource:
    #url: jdbc:postgresql://10.220.33.203:5432/jngdb1
    #username: jnguser1
    #password: jnguser1pwd

#logging.level.org.hibernate: DEBUG
