apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ZPLACEHOLDER-scg-route
  annotations:
    healthcheck.gslb.tanzu.vmware.com/service: spring-cloud-gateway
    healthcheck.gslb.tanzu.vmware.com/path: /
    healthcheck.gslb.tanzu.vmware.com/port: "80"
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: default-gateway
    sectionName: http-ZPLACEHOLDER
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: spring-cloud-gateway
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayRouteConfig
metadata:
  name: ZPLACEHOLDER-route-config
spec:
  routes:
  - predicates:
    - Path=/**
    - Method=GET
    order: 1000
    filters:
    - StripPrefix=0
    tags:
    - ZPLACEHOLDER  
  service:
    name: ZPLACEHOLDER
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: ZPLACEHOLDER-route-mapping
spec:
  gatewayRef:
    name: spring-cloud-gateway
  routeConfigRef:
    name: ZPLACEHOLDER-route-config
