apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  creationTimestamp: null
  name: exploreinclusionapp
spec:
  acceptedServiceBindings:
  - name: postgresql
    types:
    - postgresql
  build:
    buildpacks: {}
    nonSecretEnv:
    - name: BP_JVM_VERSION
      value: "17"
    path: ../..
  ports:
  - name: main
    port: 8080
